replicaCount: 1

image:
  repository: 300481/cda
  tag: latest
  pullPolicy: Always

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 10m
    memory: 32Mi

service:
  port: 80

env:
  githubSecret: none